destination: ./_site
lsi:         false
port: 4000
pygments:    true
markdown:    maruku
#permalink:   /:year/:month/:day/:title
permalink:   /:year/:month/:title

exclude: [ tools, README, .git, .gitignore ]
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
url: http://danc.alwaysdata.net
# Change the dir the individual tag files are output to
tag_dir: tag # Default is tags
# Title to be used when generating the individual tag html files prefixed with tag name
tag_title_prefix: "Tags &raquo; "
# Change the dir the individual category files are output to
category_dir: topics # Default is categories
# Title to be used when generating the individual category html files prefixed to category name
category_title_prefix: "Themes &raquo; "
#ftp_host: ftpperso.free.fr
#ftp_dir: /

